In [2]:
import numpy as np

In [3]:
#Q1) Create a null vector of size 10 but the fifth value which is 1

Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
#Q2)Create a vector with values ranging from 10 to 49.

Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
#Q3)Create a 3x3 matrix with values ranging from 0 to 8

Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#Q4)Find indices of non-zero elements from [1,2,0,0,4,0]

nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [10]:
#Q5)Create a 10x10 array with random values and find the minimum and maximum values.

Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print('Zmin=',Zmin)
print('Zmax=',Zmax)

Zmin= 0.01053801872485649
Zmax= 0.9936948654709197


In [11]:
#Q6)Create a random vector of size 30 and find the mean value

Z=np.random.random(30)
m=Z.mean()
print(m)

0.553587981751534
